name: Test Compilation

on: [pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmake-version: '3.5'

      - name: Install dependencies
        run: |
          sudo apt-get install libsfml-dev
          sudo apt-get install libboost-all-dev
          sudo apt-get install libx11-dev libxrandr-dev
          sudo apt-get install libudev-dev
          sudo apt-get install libopenal-dev
          sudo apt-get install libvorbis-dev
          sudo apt-get install libflac-dev
          sudo apt-get install libmongoc-1.0-0
          sudo apt-get install libbson-1.0
          sudo apt-get install libasio-dev
          sudo apt-get install libxcursor-dev

      - name: LINUX - Launch cmake
        run: cmake . && cmake --build .

      - name: LINUX - Launch tests
        run: cmake --build . --target my_tests

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Windows - Launch cmake
        run: cmake . && cmake --build .

      - name: WINOWS -  Launch tests
        run: cmake --build . --target my_tests
