name: Test Compilation

on: [pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmake-version: '3.5'

      - name: Install dependencies
        run: |
          sudo apt-get install libsfml-dev
          sudo apt-get install libboost-all-dev
          sudo apt-get install libx11-dev libxrandr-dev
          sudo apt-get install libudev-dev
          sudo apt-get install libopenal-dev
          sudo apt-get install libvorbis-dev
          sudo apt-get install libflac-dev
          sudo apt-get install libmongoc-1.0-0
          sudo apt-get install libbson-1.0
          sudo apt-get install libasio-dev
          sudo apt-get install libxcursor-dev

      - name: LINUX - Launch cmake
        run: cmake . && cmake --build .

      - name: LINUX - Launch tests
        run: cmake --build . --target my_tests
      
      - name: Archive Linux Executables
        uses: actions/upload-artifact@v2
        with:
          name: linux-executables
          path: path/to/linux/executables

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Windows - Launch cmake
        run: cmake . && cmake --build .

      - name: WINOWS -  Launch tests
        run: cmake --build . --target my_tests
  
  build:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:

      # - name: Move Linux executables
      #   run: |
      #     ls -a .

      #     # mkdir -p linux
      #     # cp client ./linux/
      #     # cp server ./linux/
      
      # - name: Move Windows executables
      #   run: |
      #     mkdir -p windows
      #     cp Debug/client ./windows/
      #     cp Debug/server ./windows/
      
      - name: Archive the assets folder
        run: |
          ls -a
          zip -r assets.zip assets windows linux

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - Updated client / server executables
            - Updated assets
          draft: false
          prerelease: false
          asset_overwrite: false
          exclude_sources: true


      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assets.zip
          asset_name: assets-v${{ github.run_number }}.zip
          asset_content_type: application/zip


      - name: Delete Source Code Archives
        run: |
          ASSET_ID=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases/${{ github.run_number }}/assets | jq -r '.[] | select(.name == "Source code (zip)" or .name == "Source code (tar.gz)") | .id')

          if [ -n "$ASSET_ID" ]; then
            for id in $ASSET_ID; do
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/assets/$id"
            done
          fi
