name: on_pr_merged

on: [push]
  # pull_request:
  #   types: [closed]

jobs:
  mirroring:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-CPP-500-PAR-5-2-rtype-anatole.babin.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: |
        mkdir -p build; cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build  .

    - name: Package code
      run: |
        cd build/
        cpack -G TGZ
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: |
          ${{ github.workspace }}/build/R-Type-*-Linux.tar.gz

  create-release:
    needs: [build-linux]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          body: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/Linux/*.tar.gz
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up CMake
  #     uses: lukka/get-cmake@latest
  #     with:
  #       cmake-version: '3.5'

  #   - name: Configure and build
  #     run: |
  #       mkdir build
  #       cd build
  #       cmake .
  #       cmake -B ./build -S .
  # release:
  #   # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   # needs: build
  #   steps:
  #     - name: Upload release artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: build-artifacts
  #         path: release
  # release:
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Calculate run number
  #       id: calc
  #       run: echo "::set-output name=run_number::$((${{ github.run_number }} - 152))"
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: 1.0.${{ steps.calc.outputs.run_number }}
  #         release_name: v1.0.${{ steps.calc.outputs.run_number }}
  #         body: |
  #           Automated release from GitHub Actions
  #         draft: false
  #         prerelease: false