name: mirroring

# on:
#   pull_request:
#     types:
#       - closed

on: [pull_request, push]


jobs:
  mirroring:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-CPP-500-PAR-5-2-rtype-anatole.babin.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
  release:
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release from GitHub Actions
          draft: false
          prerelease: false